import{a as u,i,S as m}from"./assets/vendor-h_xsmXee.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&s(n)}).observe(document,{childList:!0,subtree:!0});function t(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(e){if(e.ep)return;e.ep=!0;const r=t(e);fetch(e.href,r)}})();const p=u.defaults.API_KEY="49359087-343ead2b9467da8fb57304bcb",f=u.defaults.baseURL="https://pixabay.com/api/";function g(a){if(!a.trim())return console.error("Search query is empty!"),Promise.reject("Search query is empty.");const o={params:{key:p,q:a.trim(),image_type:"photo",orientation:"horizontal",safesearch:"true"}};return u.get(f,o).then(t=>{var e;return(e=t==null?void 0:t.data)==null?void 0:e.hits}).catch(t=>{console.error("API Error:",t.message);let s="An unexpected error occurred. Please try again later!";t.response?s=`Server Error: ${t.response.data.message||t.message}`:t.request&&(s="Network Error: Failed to reach the server. Please check your internet connection."),i.show({title:"⚠️",message:s,color:"red",position:"topRight"})})}const d=document.querySelector(".gallery");function y(a=[]){d.innerHTML="";const o=a.map(t=>`<li class="gallery-item">
        <a href="${t.largeImageURL}" class="gallery-item-link">
        <img class="gallery-img" src="${t.webformatURL}" alt="${t.tags}" loading="lazy" />
        </a>
        <div class="text-info">
        <p><b>Likes:</b>${t.likes}</p>
        <p><b>Views:</b>${t.views}</p>
        <p><b>Comments:</b>${t.comments}</p>
        <p><b>Downloads:</b>${t.downloads}</p>
        </div>
        </li>`).join("");d.insertAdjacentHTML("beforeend",o)}let l=null;const h=document.querySelector(".form"),c=document.querySelector(".loader");h.addEventListener("submit",b);function b(a){a.preventDefault();const o=a.currentTarget,{searchText:t}=o.elements,s=t.value.trim();if(!s){i.show({title:"⛔",message:"Please write a search query!",color:"yellow",position:"topRight"});return}c.classList.remove("hidden"),g(s).then(e=>{if(!Array.isArray(e)){console.error("Invalid response structure. Hits is not an array."),i.show({title:"⚠️",message:"Unexpected response format. Please try again later!",color:"red",position:"topRight"});return}if(e.length===0){i.show({title:"❌",message:"Sorry, there are no images matching your search query. Please try again!",color:"red",position:"topRight"}),c.classList.add("hidden");return}y(e),l?l.refresh():l=new m(".gallery a",{caption:!0,captionType:"attr",captionsData:"alt",captionPosition:"bottom",captionDelay:250}),o.reset()}).catch(e=>{console.error("Error:",e.message)}).finally(()=>{c.classList.add("hidden")})}
//# sourceMappingURL=index.js.map
