import{S as p,a as u,i}from"./assets/vendor-GIT4gZzC.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))r(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const n of o.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&r(n)}).observe(document,{childList:!0,subtree:!0});function t(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function r(e){if(e.ep)return;e.ep=!0;const o=t(e);fetch(e.href,o)}})();let l=null;const d=document.querySelector(".gallery");function m(a=[]){d.innerHTML="";const s=a.map(t=>`<li class="gallery-item">
        <a href="${t.largeImageURL}" class="gallery-item-link">
        <img class="gallery-img" src="${t.webformatURL}" alt="${t.tags}" loading="lazy" />
        </a>
        <div class="text-info">
        <p><b>Likes:</b>${t.likes}</p>
        <p><b>Views:</b>${t.views}</p>
        <p><b>Comments:</b>${t.comments}</p>
        <p><b>Downloads:</b>${t.downloads}</p>
        </div>
        </li>`).join("");d.insertAdjacentHTML("beforeend",s),l?l.refresh():l=new p(".gallery a",{caption:!0,captionType:"attr",captionsData:"alt",captionPosition:"bottom",captionDelay:250})}const g=u.defaults.API_KEY="49359087-343ead2b9467da8fb57304bcb",f=u.defaults.baseURL="https://pixabay.com/api/";function y(a){if(!a.trim())return console.error("Search query is empty!"),Promise.reject("Search query is empty.");const s={params:{key:g,q:a.trim(),image_type:"photo",orientation:"horizontal",safesearch:"true"}};return u.get(f,s).then(t=>{var e;const r=(e=t==null?void 0:t.data)==null?void 0:e.hits;if(!Array.isArray(r)){console.error("Invalid response structure. Hits is not an array."),i.show({title:"⚠️",message:"Unexpected response format. Please try again later!",color:"red",position:"topRight"});return}if(r.length===0){i.show({title:"❌",message:"Sorry, there are no images matching your search query. Please try again!",color:"red",position:"topRight"});return}return m(r),r}).catch(t=>{console.error("API Error:",t.message);let r="An unexpected error occurred. Please try again later!";t.response?r=`Server Error: ${t.response.data.message||t.message}`:t.request&&(r="Network Error: Failed to reach the server. Please check your internet connection."),i.show({title:"⚠️",message:r,color:"red",position:"topRight"})})}const h=document.querySelector(".form"),c=document.querySelector(".loader");h.addEventListener("submit",b);function b(a){a.preventDefault();const s=a.currentTarget,{searchText:t}=s.elements,r=t.value.trim();if(!r){i.show({title:"⛔",message:"Please write a search query!",color:"yellow",position:"topRight"});return}c.classList.remove("hidden"),y(r).then(e=>{if(e.length===0){i.show({title:"❌",message:"Sorry, there are no images matching your search query. Please try again!",color:"red",position:"topRight"}),c.classList.add("hidden");return}m(e),s.reset()}).catch(e=>{console.error("Error:",e.message),i.show({title:"⚠️",message:"An unexpected error occurred. Please try again later!",color:"blue",position:"topRight"})}).finally(()=>{c.classList.add("hidden")})}
//# sourceMappingURL=index.js.map
